-- Create quiz questions table
CREATE TABLE public.quiz_questions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_answer_index INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;

-- Everyone can view questions
CREATE POLICY "Everyone can view quiz questions" 
ON public.quiz_questions 
FOR SELECT 
USING (true);

-- Insert a large variety of Christmas quiz questions
INSERT INTO public.quiz_questions (question, options, correct_answer_index) VALUES
('What is the most popular Christmas carol of all time?', '["Jingle Bells", "Silent Night", "White Christmas", "Deck the Halls"]', 1),
('In which country did the tradition of the Christmas tree originate?', '["USA", "Germany", "England", "France"]', 1),
('What are the traditional colors of Christmas?', '["Blue and Silver", "Red and Green", "Gold and White", "Purple and Pink"]', 1),
('How many reindeer pull Santa''s sleigh (including Rudolph)?', '["8", "9", "10", "12"]', 1),
('What is traditionally hidden inside a Christmas pudding?', '["A ring", "A coin", "A button", "A thimble"]', 1),
('What year was ''Jingle Bells'' written?', '["1857", "1900", "1920", "1945"]', 0),
('Which country started the tradition of putting up a Christmas tree?', '["Norway", "Germany", "Poland", "Austria"]', 1),
('What does Santa fill stockings with if children are naughty?', '["Nothing", "Coal", "Rocks", "Sticks"]', 1),
('What is Frosty the Snowman''s nose made of?', '["A carrot", "A button", "A coal", "A stick"]', 1),
('How many ghosts visit Scrooge in ''A Christmas Carol''?', '["3", "4", "5", "2"]', 1),
('What Christmas decoration was originally made from silver?', '["Ornaments", "Tinsel", "Garland", "Stars"]', 1),
('What is the name of the Grinch''s dog?', '["Max", "Buddy", "Rex", "Spot"]', 0),
('Which country does St. Nicholas come from?', '["Finland", "Turkey", "Greece", "Russia"]', 1),
('What do people traditionally put on top of a Christmas tree?', '["A star", "An angel", "A bow", "Both A and B"]', 3),
('In ''Home Alone'', where are the McCallisters going on vacation?', '["London", "Paris", "Rome", "Madrid"]', 1),
('What is the name of the movie where a boy takes a train to the North Pole?', '["The Polar Express", "Elf", "Arthur Christmas", "The Santa Clause"]', 0),
('In which month is Christmas celebrated in Australia?', '["December (Summer)", "June (Winter)", "March", "September"]', 0),
('What fruit is traditionally put in Christmas stockings?', '["Apple", "Orange", "Banana", "Grapes"]', 1),
('What beverage is left out for Santa?', '["Coffee", "Milk", "Hot Chocolate", "Water"]', 1),
('What is the name of Rudolph''s girlfriend?', '["Clarice", "Clara", "Christine", "Carol"]', 0),
('Which famous Christmas song was originally written for Thanksgiving?', '["Jingle Bells", "Deck the Halls", "Silent Night", "O Holy Night"]', 0),
('What are Christmas carolers also known as?', '["Wailers", "Singers", "Waits", "Carolists"]', 2),
('What plant is associated with Christmas kisses?', '["Holly", "Mistletoe", "Ivy", "Pine"]', 1),
('How many gifts were given in ''The Twelve Days of Christmas''?', '["144", "364", "78", "12"]', 1),
('What is the highest-grossing Christmas movie of all time?', '["The Grinch (2018)", "Home Alone", "Elf", "The Polar Express"]', 0),
('In which country is KFC a traditional Christmas meal?', '["USA", "UK", "Japan", "China"]', 2),
('What is the name of the angel in ''It''s a Wonderful Life''?', '["Clarence", "Gabriel", "Michael", "Raphael"]', 0),
('What was the first company to use Santa Claus in advertising?', '["Pepsi", "Coca-Cola", "Sprite", "7-Up"]', 1),
('What is the name of Santa''s home?', '["North Pole", "Lapland", "Iceland", "Greenland"]', 0),
('In ''A Christmas Story'', what gift does Ralphie want?', '["A bicycle", "A Red Ryder BB gun", "A train set", "A puppy"]', 1),
('Which country gives a Christmas tree to London every year?', '["Sweden", "Norway", "Finland", "Denmark"]', 1),
('What is the shortest day of the year called?', '["Winter Solstice", "Christmas Eve", "New Year", "Boxing Day"]', 0),
('What color are Santa''s boots traditionally?', '["Brown", "Black", "Red", "White"]', 1),
('In ''Elf'', what is Buddy''s favorite food group?', '["Cookies", "Candy", "Chocolate", "Ice cream"]', 1),
('What Christmas decoration is actually a parasitic plant?', '["Holly", "Mistletoe", "Ivy", "Poinsettia"]', 1),
('How long does it take for a Christmas tree to grow?', '["5 years", "15 years", "25 years", "10 years"]', 1),
('What is the best-selling Christmas single of all time?', '["Last Christmas", "All I Want for Christmas Is You", "White Christmas", "Jingle Bell Rock"]', 2),
('In the song ''12 Days of Christmas'', what is given on the 7th day?', '["Seven swans a-swimming", "Seven geese a-laying", "Seven lords a-leaping", "Seven ladies dancing"]', 0),
('What is Santa Claus called in France?', '["Papa Noel", "Pere Noel", "Saint Nicolas", "Bon Papa"]', 1),
('Which reindeer shares a name with another holiday mascot?', '["Cupid", "Comet", "Dasher", "Blitzen"]', 0),
('What is the name of the head elf in ''The Santa Clause''?', '["Bernard", "Bob", "Billy", "Ben"]', 0),
('In ''The Nightmare Before Christmas'', who is the Pumpkin King?', '["Jack Skellington", "Oogie Boogie", "Zero", "Lock"]', 0),
('What is traditionally placed inside a Christmas cracker?', '["A joke", "Money", "Candy", "A key"]', 0),
('Which country celebrates Christmas with a witch named Befana?', '["Spain", "Italy", "Greece", "Portugal"]', 1),
('What is eggnog made from?', '["Eggs, milk, and sugar", "Eggs, cream, and rum", "Milk, sugar, and vanilla", "Cream, eggs, and brandy"]', 0),
('In ''Rudolph the Red-Nosed Reindeer'', what is the name of the elf who wants to be a dentist?', '["Hermey", "Harry", "Henry", "Harold"]', 0),
('What is the day after Christmas called in the UK?', '["Boxing Day", "Christmas Day 2", "St. Stephen''s Day", "Winter Day"]', 0),
('How do you say ''Merry Christmas'' in Spanish?', '["Feliz Navidad", "Buon Natale", "Frohe Weihnachten", "Joyeux Noel"]', 0),
('What is the Grinch''s heart said to be how many sizes too small?', '["One", "Two", "Three", "Four"]', 1),
('In the movie ''Elf'', what is the first rule of ''The Code of Elves''?', '["Treat every day like Christmas", "There''s room for everyone on the nice list", "The best way to spread Christmas cheer is singing loud for all to hear", "Never eat yellow snow"]', 0),
('What Christmas-themed ballet premiered in Russia in 1892?', '["Swan Lake", "The Nutcracker", "Sleeping Beauty", "Cinderella"]', 1),
('What is the name of the train in ''The Polar Express''?', '["The North Pole Express", "The Polar Express", "The Christmas Express", "The Magic Train"]', 1),
('In ''How the Grinch Stole Christmas'', what is the name of the town?', '["Whoville", "Snowville", "Christmastown", "Hollyville"]', 0),
('What popular Christmas song was actually written for Easter?', '["Jingle Bells", "Here Comes Santa Claus", "White Christmas", "None - this is a myth"]', 3),
('Which fairy tale inspired gingerbread houses?', '["Hansel and Gretel", "Snow White", "Cinderella", "Little Red Riding Hood"]', 0),
('What are the two most popular Christmas tree toppers?', '["Star and Angel", "Star and Santa", "Angel and Bell", "Cross and Star"]', 0),
('In what year did Christmas become a federal holiday in the US?', '["1870", "1800", "1900", "1850"]', 0),
('What is the name of Santa''s workshop?', '["Santa''s Factory", "North Pole Workshop", "Christmas Central", "Toy Land"]', 1),
('What is the Christmas flower?', '["Rose", "Poinsettia", "Lily", "Tulip"]', 1),
('Which country started the tradition of the Advent calendar?', '["Austria", "Germany", "Switzerland", "Netherlands"]', 1),
('What meat is traditionally served at a British Christmas dinner?', '["Chicken", "Turkey", "Ham", "Goose"]', 1),
('In ''Frosty the Snowman'', what made Frosty come to life?', '["A scarf", "An old silk hat", "A magic wand", "Children''s wishes"]', 1),
('What is the name of the little girl in ''The Nutcracker''?', '["Clara", "Lucy", "Sophie", "Emma"]', 0),
('How many times does Santa check his list?', '["Once", "Twice", "Three times", "Four times"]', 1),
('What do naughty children get in their stockings?', '["Nothing", "Coal", "Potatoes", "Sticks"]', 1),
('What Christmas beverage is also called ''milk punch''?', '["Hot chocolate", "Eggnog", "Mulled wine", "Wassail"]', 1),
('In the song ''Winter Wonderland'', who do we pretend the snowman is?', '["Santa Claus", "Parson Brown", "Jack Frost", "Frosty"]', 1),
('Which US state was the first to recognize Christmas as an official holiday?', '["Alabama", "Texas", "New York", "Virginia"]', 0),
('What is the name of the last ghost in ''A Christmas Carol''?', '["Ghost of Christmas Future", "Ghost of Christmas Yet to Come", "Ghost of Christmas Past", "Spirit of the Future"]', 1),
('In ''National Lampoon''s Christmas Vacation'', what does Clark want to buy with his Christmas bonus?', '["A new car", "A pool", "A boat", "A vacation home"]', 1),
('What is the Christmas zodiac sign?', '["Sagittarius", "Capricorn", "Both", "Aquarius"]', 2),
('Which popular Christmas toy is based on a 1903 political caricature?', '["Teddy Bear", "Jack-in-the-box", "Rocking horse", "Toy soldier"]', 0),
('What is the name of George Bailey''s guardian angel in ''It''s a Wonderful Life''?', '["Clarence Odbody", "Gabriel Smith", "Michael Jones", "Raphael Brown"]', 0),
('What is the Ukrainian tradition of decorating Christmas trees with?', '["Ornaments", "Spider webs", "Flowers", "Ribbons"]', 1),
('In which ocean is Christmas Island located?', '["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"]', 2),
('What is the name of the evil magician in ''Frosty the Snowman''?', '["Professor Hinkle", "Mr. Freeze", "Ice King", "Dr. Cold"]', 0),
('What is the name of Scrooge''s deceased business partner?', '["Jacob Marley", "Bob Cratchit", "Fred", "Tim"]', 0),
('How do you say ''Merry Christmas'' in Italian?', '["Feliz Navidad", "Buon Natale", "Frohe Weihnachten", "Joyeux Noel"]', 1),
('What is the most recorded Christmas song?', '["White Christmas", "Silent Night", "Jingle Bells", "Joy to the World"]', 1),
('In ''Rudolph the Red-Nosed Reindeer'', what is the Island of Misfit Toys ruler''s name?', '["King Moonracer", "King Sunlight", "King Starshine", "King Comet"]', 0),
('What fruit was traditionally put in Christmas stockings?', '["Apples", "Oranges", "Pears", "Plums"]', 1),
('What Christmas song contains the lyric ''Everyone dancing merrily in the new old-fashioned way''?', '["Rockin'' Around the Christmas Tree", "Jingle Bell Rock", "Holly Jolly Christmas", "Winter Wonderland"]', 0),
('What is the name of the Grinch''s love interest?', '["Martha May Whovier", "Betty Lou Who", "Cindy Lou Who", "Mary Who"]', 0),
('How many candles are on an Advent wreath?', '["3", "4", "5", "6"]', 1),
('What is the name of the Christmas special featuring Snoopy?', '["A Charlie Brown Christmas", "Snoopy''s Christmas", "Peanuts Christmas", "The Beagle Christmas"]', 0),
('In ''The Santa Clause'', what does Scott Calvin do for a living?', '["Lawyer", "Toy maker", "Marketing executive", "Teacher"]', 2),
('What country is the poinsettia native to?', '["USA", "Mexico", "Canada", "Spain"]', 1),
('What is the shortest day of the year?', '["December 21", "December 22", "December 23", "December 24"]', 0),
('What is the name of the Scrooge''s nephew in ''A Christmas Carol''?', '["Fred", "Bob", "Tim", "Peter"]', 0),
('In ''A Christmas Story'', what does Ralphie''s aunt make him for Christmas?', '["A scarf", "A pink bunny suit", "Mittens", "A hat"]', 1),
('What is the German name for the song ''O Christmas Tree''?', '["O Tannenbaum", "O Weihnachtsbaum", "Der Christbaum", "O Baum"]', 0),
('What do people in Japan traditionally eat for Christmas dinner?', '["Sushi", "KFC", "Ramen", "Tempura"]', 1),
('What is wassailing?', '["Decorating trees", "Singing Christmas carols", "Making snow angels", "Building snowmen"]', 1),
('What is the name of the main villain in ''The Nightmare Before Christmas''?', '["Oogie Boogie", "Lock", "Shock", "Barrel"]', 0),
('How many towns in America are named ''Christmas''?', '["1", "2", "3", "4"]', 1),
('What is the name of the little boy in ''The Polar Express''?', '["Hero Boy", "Chris", "Billy", "Tommy"]', 0),
('In ''Miracle on 34th Street'', what department store does Kris Kringle work in?', '["Macy''s", "Bloomingdale''s", "Saks", "Nordstrom"]', 0),
('What is the day before Christmas called?', '["Christmas Eve", "Christmas Day", "Boxing Day", "St. Nicholas Day"]', 0);